name: Gradle Dependency Submission

on:
  push:
    branches:
      - develop

jobs:
  gradle-action-detection:
    name: Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle dependency submission
        uses: mikepenz/gradle-dependency-submission@v0.8.4
        with:
          gradle-build-module: |-
            :app
            :bili-api
            :bili-subtitle
          sub-module-mode: INDIVIDUAL