name: Alpha Build

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build-alpha:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Write google-services.json
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Add signing properties
        env:
          SIGNING_PROPERTIES: ${{ secrets.SIGNING_PROPERTIES }}
        run: |
          echo ${{ secrets.SIGNING_PROPERTIES }} > encoded_signing_properties
          base64 -d encoded_signing_properties > signing.properties

      - name: Add jks file
        run: |
          echo ${{ secrets.SIGN_KEY }} > ./encoded_key
          base64 -d encoded_key > key.jks

      - name: Build apk
        run: ./gradlew assembleAlpha assembleDebug

      - name: Read alpha apk output metadata
        id: apk-meta-alpha
        uses: juliangruber/read-file-action@v1
        with:
          path: app/build/outputs/apk/alpha/output-metadata.json

      - name: Read debug apk output metadata
        id: apk-meta-debug
        uses: juliangruber/read-file-action@v1
        with:
          path: app/build/outputs/apk/debug/output-metadata.json

      - name: Parse package info
        id: package-info
        run: |
          echo "alpha_info_apk_filename=${{ fromJson(steps.apk-meta-alpha.outputs.content).elements[0].outputFile }}" >> $GITHUB_ENV
          echo "debug_info_apk_filename=${{ fromJson(steps.apk-meta-debug.outputs.content).elements[0].outputFile }}" >> $GITHUB_ENV

      - name: Archive alpha build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Alpha build artifact
          path: app/build/outputs/apk/alpha/${{ env.alpha_info_apk_filename }}

      - name: Archive alpha build mappings
        uses: actions/upload-artifact@v3
        with:
          name: Alpha build mappings
          path: app/build/outputs/mapping/alpha

      - name: Archive debug build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Debug build artifact
          path: app/build/outputs/apk/debug/${{ env.debug_info_apk_filename }}
